
INSERT INTO pizzeriadb.pizza VALUES (1,'PIZZA HAWAINA','PIZZA HAWAINA');
INSERT INTO pizzeriadb.pizza VALUES (2,'PIZZA AMERICANA','PIZZA AMERICANA');
INSERT INTO pizzeriadb.pizza VALUES (3,'PIZZA VEGETARIANA','PIZZA VEGETARIANA');
INSERT INTO pizzeriadb.pizza VALUES (4,'PIZZA ITALIANA','PIZZA ITALIANA');

SELECT * FROM pizzeriadb.pizza;